# TODO setup flyway migrations
spring:
  datasource:
    url: jdbc:h2:file:~/h2/data/orders;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  kafka:
    topic:
      new-order-received: order.new-order-received
      process-order-payment: order.process-order-payment
      new-order-approved: order.new-order-approved
      order-products-reserved: stock.order-products-reserved
      order-products-reservation-failed: stock.order-products-reservation-failed
      order-payment-processed: payment.order-payment-processed
      order-payment-failed: payment.order-payment-failed
    consumer-group-id: orders.ms
    bootstrap-servers: 127.0.0.1:9092
hibernate:
  enable_lazy_load_no_trans: true
server:
  port: 8210
