# TODO setup flyway migrations
spring:
  # mysql spring data source
  datasource:
    url: jdbc:mysql://mysql:3306/aos?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  kafka:
    topic:
      new-order-received: order.new-order-received
      process-order-payment: order.process-order-payment
      new-order-approved: order.new-order-approved
      order-products-reserved: stock.order-products-reserved
      order-products-reservation-failed: stock.order-products-reservation-failed
      order-payment-processed: payment.order-payment-processed
      order-payment-failed: payment.order-payment-failed
    consumer-group-id: orders.ms
    bootstrap-servers: kafka:9092
hibernate:
  enable_lazy_load_no_trans: true
server:
  port: 8210
